### ISSUE TITLE
/clean не различает int и не-int как аргументы

### ISSUE THREAD

**Issue by iglunchadze** [arvego/mm-randbot#36]
После вызова `/clean @AChekhonte` (по приколу):
```
Traceback (most recent call last):
  File "mm-randbot.py", line 192, in <module>
    my_bot.polling(none_stop=True, interval=1, timeout=60)
  File "/home/ramzan.bekbulatov/bin/anaconda3/lib/python3.6/site-packages/telebot/__init__.py", line 266, in polling
    self.__non_threaded_polling(none_stop, interval, timeout)
  File "/home/ramzan.bekbulatov/bin/anaconda3/lib/python3.6/site-packages/telebot/__init__.py", line 317, in __non_threaded_polling
    self.__retrieve_updates(timeout)
  File "/home/ramzan.bekbulatov/bin/anaconda3/lib/python3.6/site-packages/telebot/__init__.py", line 160, in __retrieve_updates
    self.process_new_updates(updates)
  File "/home/ramzan.bekbulatov/bin/anaconda3/lib/python3.6/site-packages/telebot/__init__.py", line 197, in process_new_updates
    self.process_new_messages(new_messages)
  File "/home/ramzan.bekbulatov/bin/anaconda3/lib/python3.6/site-packages/telebot/__init__.py", line 218, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/home/ramzan.bekbulatov/bin/anaconda3/lib/python3.6/site-packages/telebot/__init__.py", line 1208, in _notify_command_handlers
    self._exec_task(message_handler['function'], message)
  File "/home/ramzan.bekbulatov/bin/anaconda3/lib/python3.6/site-packages/telebot/__init__.py", line 339, in _exec_task
    task(*args, **kwargs)
  File "mm-randbot.py", line 133, in admin_toys
    admin_tools.admin_toys(message)
  File "/home/ramzan.bekbulatov/study/mm-randbot-test/commands/admin_tools.py", line 93, in admin_toys
    admin_clean(message)
  File "/home/ramzan.bekbulatov/study/mm-randbot-test/commands/admin_tools.py", line 44, in admin_clean
    num_of_messages = int(message.text.split()[1])
ValueError: invalid literal for int() with base 10: '@AChekhonte'
```

**Comment by iglunchadze** [comment]
Коммит f7d09d0. Тестим.
